metadata author = {
	fullName: 'Stas Sultanov'
	profiles: {
		gitHub: 'https://github.com/stas-sultanov'
		linkedIn: 'https://www.linkedin.com/in/stas-sultanov'
	}
}
metadata description = 'Provisions a Microsoft.ContainerRegistry/registries resource with extensions.'

/* IMPORTS */

import * as AuthorizationRoleAssignments from '../../../library/Authorization/roleAssignments.bicep'

import * as InsightsDiagnosticSetting from '../../../library/Insights/diagnosticSettings.bicep'

/* PARAMETERS */

@description('The extensions settings.')
@sealed()
param extensions {
	Authorization: {
		roleAssignments: AuthorizationRoleAssignments.ResourceInput[]?
	}?
	Insights: {
		diagnosticSettings: InsightsDiagnosticSetting.Resource[]
	}
}

@description('The resource settings.')
@sealed()
param settings {
	@description('The identity.')
	identity: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.identity?
	@description('The geo-location.')
	location: string
	@description('The name.')
	name: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.name
	@description('The configurable properties.')
	@sealed()
	properties: {
		@description('Enable a single data endpoint per region for serving data. Premium SKU only.')
		dataEndpointEnabled: bool?
		@description('The auto-generated domain name label scope.')
		autoGeneratedDomainNameLabelScope: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.autoGeneratedDomainNameLabelScope
		@description('The endpoint protocol settings for the registry login server and data endpoints.')
		endpointProtocol: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.endpointProtocol
		@description('The metadata search setting')
		metadataSearch: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.metadataSearch
		@description('Whether or not Tasks allowed to bypass the network rules for this container registry. Requires: sku.name == \'Premium\'.')
		networkRuleBypassAllowedForTasks: bool?
		@description('Whether to allow trusted Azure services to access a network restricted registry. Requires: sku.name == \'Premium\'.')
		networkRuleBypassOptions: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.networkRuleBypassOptions?
		@description('The network rule set. Requires: sku.name == \'Premium\'.')
		networkRuleSet: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.networkRuleSet?
		@description('The policies.')
		policies: {
			@description('The export policy. Requires: sku.name == \'Premium\' && properties.publicNetworkAccess == \'Disabled\'.')
			exportPolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.policies.exportPolicy
			@description('The quarantine policy.')
			quarantinePolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.policies.quarantinePolicy
			@description('The retention policy. Requires: sku.name == \'Premium\'.')
			retentionPolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.policies.retentionPolicy
			@description('The soft-delete policy.')
			softDeletePolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.policies.softDeletePolicy
		}
		@description('The network access mode.')
		publicNetworkAccess: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.publicNetworkAccess
		@description('Whether or not regional endpoints are enabled.')
		regionalEndpoints: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.regionalEndpoints
		@description('Whether or not zone redundancy is enabled. Requires: sku.name == \'Premium\'.')
		zoneRedundancy: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.zoneRedundancy
	}
	@description('The SKU.')
	sku: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.sku
	@description('The tags.')
	tags: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.tags
}

/* VARIABLES */

var isPremiumSku = settings.sku.name == 'Premium'
var isZoneRedundancySupported = isPremiumSku

/* RESOURCES */

#disable-next-line use-recent-api-versions // endpointProtocol, metadataSearch, and regionalEndpoints are available only in the preview API.
resource ContainerRegistry_registries_ 'Microsoft.ContainerRegistry/registries@2026-03-01-preview' = {
	identity: settings.?identity ?? {
	type: 'None'
}
	location: settings.location
	name: settings.name
	properties: {
		adminUserEnabled: false
		anonymousPullEnabled: false
		autoGeneratedDomainNameLabelScope: settings.properties.autoGeneratedDomainNameLabelScope
		dataEndpointEnabled: isPremiumSku
			? settings.properties.?dataEndpointEnabled
			: null
		endpointProtocol: settings.properties.endpointProtocol
		metadataSearch: settings.properties.metadataSearch
		networkRuleBypassAllowedForTasks: isPremiumSku
			? settings.properties.?networkRuleBypassAllowedForTasks
			: null
		networkRuleBypassOptions: isPremiumSku
			? settings.properties.?networkRuleBypassOptions
			: null
		networkRuleSet: isPremiumSku
			? settings.properties.?networkRuleSet
			: null
		policies: {
			azureADAuthenticationAsArmPolicy: {
				status: 'enabled'
			}
			exportPolicy: isPremiumSku && settings.properties.publicNetworkAccess == 'Disabled'
				? settings.properties.policies.exportPolicy
				: null
			quarantinePolicy: settings.properties.policies.quarantinePolicy
			retentionPolicy: isPremiumSku
				? settings.properties.policies.retentionPolicy
				: null
			softDeletePolicy: settings.properties.policies.softDeletePolicy
		}
		publicNetworkAccess: settings.properties.publicNetworkAccess
		regionalEndpoints: settings.properties.regionalEndpoints
		roleAssignmentMode: 'AbacRepositoryPermissions'
		zoneRedundancy: isZoneRedundancySupported
			? settings.properties.zoneRedundancy
			: null
	}
	sku: settings.sku
	tags: settings.tags
}

/* EXTENSIONS */

resource Authorization_roleAssignments_ 'Microsoft.Authorization/roleAssignments@2022-04-01' = [
	for item in AuthorizationRoleAssignments.CreateArray(
		ContainerRegistry_registries_.id,
		extensions.?Authorization.?roleAssignments ?? []
	): {
		name: item.name
		properties: item.properties
		scope: ContainerRegistry_registries_
	}
]

#disable-next-line use-recent-api-versions // 2021-05-01-preview is the newest Diagnostic Settings API; the newest stable version is 2016-09-01.
resource Insights_diagnosticSettings_ 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = [
	for item in extensions.Insights.diagnosticSettings: {
		name: item.name
		properties: item.properties
		scope: ContainerRegistry_registries_
	}
]

/* OUTPUTS */

@description('The id.')
output id string = ContainerRegistry_registries_.id

@description('The identity.')
output identity resourceOutput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.identity? = ContainerRegistry_registries_.?identity

@description('The name.')
output name string = ContainerRegistry_registries_.name
