metadata author = {
	fullName: 'Stas Sultanov'
	profiles: {
		gitHub: 'https://github.com/stas-sultanov'
		linkedIn: 'https://www.linkedin.com/in/stas-sultanov'
	}
}
metadata description = 'Provisions a Microsoft.ContainerRegistry/registries resource.'

/* IMPORTS */

import * as AuthorizationRoleAssignments from '../../../library/Authorization/roleAssignments.bicep'

import * as InsightsDiagnosticSetting from '../../../library/Insights/diagnosticSettings.bicep'

/* PARAMETERS */

@description('The extensions settings.')
@sealed()
param extensions {
	Authorization: {
		roleAssignments: AuthorizationRoleAssignments.ResourceInput[]?
	}?
	Insights: {
		diagnosticSettings: InsightsDiagnosticSetting.Resource[]
	}
}

@description('The identity.')
param identity resourceInput<'Microsoft.ContainerRegistry/registries@2025-11-01'>.identity = {
	type: 'None'
}

@description('The geo-location.')
param location string

@description('The name.')
param name string

@description('The configurable properties.')
@sealed()
param properties {
	@description('Enable a single data endpoint per region for serving data. Premium SKU only.')
	dataEndpointEnabled: bool?
	@description('The auto-generated domain name label scope.')
	autoGeneratedDomainNameLabelScope: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.autoGeneratedDomainNameLabelScope
	@description('The endpoint protocol settings for the registry login server and data endpoints.')
	endpointProtocol: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.endpointProtocol
	@description('The metadata search setting')
	metadataSearch: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.metadataSearch
	@description('Whether or not Tasks allowed to bypass the network rules for this container registry. Requires: sku.name == \'Premium\'.')
	networkRuleBypassAllowedForTasks: bool?
	@description('Whether to allow trusted Azure services to access a network restricted registry. Requires: sku.name == \'Premium\'.')
	networkRuleBypassOptions: resourceInput<'Microsoft.ContainerRegistry/registries@2025-11-01'>.properties.networkRuleBypassOptions?
	@description('The network rule set. Requires: sku.name == \'Premium\'.')
	networkRuleSet: resourceInput<'Microsoft.ContainerRegistry/registries@2025-11-01'>.properties.networkRuleSet?
	@description('The policies.')
	policies: {
		@description('The export policy. Requires: sku.name == \'Premium\' && properties.publicNetworkAccess == \'Disabled\'.')
		exportPolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2025-11-01'>.properties.policies.exportPolicy
		@description('The quarantine policy.')
		quarantinePolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2025-11-01'>.properties.policies.quarantinePolicy
		@description('The retention policy. Requires: sku.name == \'Premium\'.')
		retentionPolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2025-11-01'>.properties.policies.retentionPolicy
		@description('The soft-delete policy.')
		softDeletePolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.policies.softDeletePolicy
	}
	@description('The network access mode.')
	publicNetworkAccess: resourceInput<'Microsoft.ContainerRegistry/registries@2025-11-01'>.properties.publicNetworkAccess
	@description('Whether or not regional endpoints are enabled.')
	regionalEndpoints: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.regionalEndpoints
	@description('Whether or not zone redundancy is enabled. Requires: sku.name == \'Premium\'.')
	zoneRedundancy: resourceInput<'Microsoft.ContainerRegistry/registries@2025-11-01'>.properties.zoneRedundancy
}

@description('The SKU.')
param sku resourceInput<'Microsoft.ContainerRegistry/registries@2025-11-01'>.sku

@description('The tags.')
param tags resourceInput<'Microsoft.ContainerRegistry/registries@2025-11-01'>.tags

/* VARIABLES */

var isPremiumSku = sku.name == 'Premium'
var isZoneRedundancySupported = isPremiumSku

/* RESOURCES */

#disable-next-line use-recent-api-versions // to use new features, preview version of resource is required
resource ContainerRegistry_registries_ 'Microsoft.ContainerRegistry/registries@2026-03-01-preview' = {
	identity: identity
	location: location
	name: name
	properties: {
		adminUserEnabled: false
		anonymousPullEnabled: false
		autoGeneratedDomainNameLabelScope: properties.autoGeneratedDomainNameLabelScope
		dataEndpointEnabled: isPremiumSku
			? properties.?dataEndpointEnabled
			: null
		endpointProtocol: properties.endpointProtocol
		metadataSearch: properties.metadataSearch
		networkRuleBypassAllowedForTasks: isPremiumSku
			? properties.?networkRuleBypassAllowedForTasks
			: null
		networkRuleBypassOptions: isPremiumSku
			? properties.?networkRuleBypassOptions
			: null
		networkRuleSet: isPremiumSku
			? properties.?networkRuleSet
			: null
		policies: {
			azureADAuthenticationAsArmPolicy: {
				status: 'enabled'
			}
			exportPolicy: isPremiumSku && properties.publicNetworkAccess == 'Disabled'
				? properties.policies.exportPolicy
				: null
			quarantinePolicy: properties.policies.quarantinePolicy
			retentionPolicy: isPremiumSku
				? properties.policies.retentionPolicy
				: null
			softDeletePolicy: properties.policies.softDeletePolicy
		}
		publicNetworkAccess: properties.publicNetworkAccess
		regionalEndpoints: properties.regionalEndpoints
		roleAssignmentMode: 'AbacRepositoryPermissions'
		zoneRedundancy: isZoneRedundancySupported
			? properties.zoneRedundancy
			: null
	}
	sku: sku
	tags: tags
}

/* EXTENSIONS */

resource Authorization_roleAssignments_ 'Microsoft.Authorization/roleAssignments@2022-04-01' = [
	for extension in AuthorizationRoleAssignments.CreateArray(
		ContainerRegistry_registries_.id,
		extensions.?Authorization.?roleAssignments ?? []
	): {
		name: extension.name
		properties: extension.properties
		scope: ContainerRegistry_registries_
	}
]

#disable-next-line use-recent-api-versions // to use new features, preview version of resource is required
resource Insights_diagnosticSettings_ 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = [
	for extension in extensions.Insights.diagnosticSettings: {
		name: extension.name
		properties: extension.properties
		scope: ContainerRegistry_registries_
	}
]

/* OUTPUTS */

@description('The id.')
output id string = ContainerRegistry_registries_.id

@description('The identity.')
output identity resourceOutput<'Microsoft.ContainerRegistry/registries@2025-11-01'>.identity? = ContainerRegistry_registries_.?identity

@description('The name.')
output name string = ContainerRegistry_registries_.name
