metadata author = {
	fullName: 'Stas Sultanov'
	profile: 'https://github.com/stas-sultanov'
}
metadata description = 'Provisions a Microsoft.Cdn/profiles/afdEndpoints resource.'

/* PARAMETERS */

@description('Name of the Cdn/profiles resource.')
param Cdn_profiles__name string

@description('Name of the resource.')
param name string

@description('Name of the Network/dnsZones resource.')
param Network_dnsZones__name string

@description('Time to live of the custom CNAME record in seconds.')
@maxValue(86400)
@minValue(1)
param network_dnsZones_cname__TTL int = 3600

@description('Time to live of the validation TXT record in seconds.')
@maxValue(86400)
@minValue(1)
param network_dnsZones_txt__TTL int = 3600

@description('Tags to put on the resources.')
param tags object

/* EXISTING RESOURCES */

resource Cdn_profiles_ 'Microsoft.Cdn/profiles@2025-06-01' existing = {
	name: Cdn_profiles__name
}

resource Network_dnsZones_ 'Microsoft.Network/dnsZones@2018-05-01' existing = {
	name: Network_dnsZones__name
}

/* RESOURCES */

resource Cdn_profiles_afdEndpoints_ 'Microsoft.Cdn/profiles/afdEndpoints@2025-06-01' = {
	location: 'global'
	name: name
	parent: Cdn_profiles_
	properties: {
		autoGeneratedDomainNameLabelScope: 'ResourceGroupReuse'
	}
	tags: tags
}

resource Cdn_profiles_customDomains_ 'Microsoft.Cdn/profiles/customDomains@2025-06-01' = {
	name: name
	parent: Cdn_profiles_
	properties: {
		azureDnsZone: {
			id: Network_dnsZones_.id
		}
		hostName: '${name}.${Network_dnsZones_.name}'
		tlsSettings: {
			certificateType: 'ManagedCertificate'
			minimumTlsVersion: 'TLS12'
		}
	}
}

resource Network_dnsZones_cname_ 'Microsoft.Network/dnsZones/CNAME@2018-05-01' = {
	name: name
	parent: Network_dnsZones_
	properties: {
		TTL: network_dnsZones_cname__TTL
		targetResource: {
			id: Cdn_profiles_afdEndpoints_.id
		}
	}
}

resource Network_dnsZones_txt_ 'Microsoft.Network/dnsZones/TXT@2018-05-01' = {
	name: '_dnsauth.${name}'
	parent: Network_dnsZones_
	properties: {
		TTL: network_dnsZones_txt__TTL
		TXTRecords: [
			{
				value: [
					Cdn_profiles_customDomains_.properties.validationProperties.validationToken
				]
			}
		]
	}
}

/* OUTPUTS */

@description('The Cdn_profiles_afdEndpoints__name.')
output Cdn_profiles_afdEndpoints__name string = Cdn_profiles_afdEndpoints_.name

@description('The Cdn_profiles_customDomains__name.')
output Cdn_profiles_customDomains__name string = Cdn_profiles_customDomains_.name

@description('The Network_dnsZones_cname__name.')
output Network_dnsZones_cname__name string = Network_dnsZones_cname_.name

@description('The Network_dnsZones_txt__name.')
output Network_dnsZones_txt__name string = Network_dnsZones_txt_.name
