metadata author = {
	fullName: 'Stas Sultanov'
	profiles: {
		gitHub: 'https://github.com/stas-sultanov'
		linkedIn: 'https://www.linkedin.com/in/stas-sultanov'
	}
}
metadata description = 'Provisions a Microsoft.ContainerRegistry/registries resource with extensions.'

/* SCOPE */

targetScope = 'resourceGroup'

/* IMPORTS */

import * as AuthorizationRoleAssignments from '../../../library/Authorization/roleAssignments.bicep'

import * as InsightsDiagnosticSetting from '../../../library/Insights/diagnosticSettings.bicep'

/* PARAMETERS */

@description('The extensions settings.')
@sealed()
param extensions {
	@sealed()
	Authorization: {
		roleAssignments: AuthorizationRoleAssignments.ResourceInput[]
	}?
	@sealed()
	Insights: {
		diagnosticSettings: InsightsDiagnosticSetting.Resource[]
	}
}

@description('The resource settings.')
@sealed()
@validate(
	value =>
		value.sku.name == 'Premium' || (value.properties.?dataEndpointEnabled != true && value.properties.?networkRuleSet == null && value.properties.policies.exportPolicy.?status != 'disabled' && value.properties.policies.retentionPolicy.?status != 'enabled' && value.properties.regionalEndpoints != 'Enabled' && value.properties.endpointProtocol != 'IPv4AndIPv6'),
	'SKU Premium is required for dataEndpointEnabled, networkRuleSet, exportPolicy, retentionPolicy, regionalEndpoints, and endpointProtocol == IPv4AndIPv6.'
)
param settings {
	@description('The identity.')
	identity: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.identity?
	@description('The geo-location.')
	location: string
	@description('The name.')
	name: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.name
	@description('The configurable properties.')
	@sealed()
	@validate(
		value =>
			(value.endpointProtocol != 'IPv4AndIPv6' || value.?dataEndpointEnabled == true) && (value.policies.exportPolicy.?status != 'disabled' || value.publicNetworkAccess == 'Disabled'),
		'IPv6 dual-stack requires dataEndpointEnabled to be true; disabling exports requires publicNetworkAccess to be Disabled.'
	)
	properties: {
		@description('The auto-generated domain name label scope.')
		autoGeneratedDomainNameLabelScope: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.autoGeneratedDomainNameLabelScope
		@description('Specifies whether dedicated data endpoints are enabled. Enabling them requires the Premium SKU.')
		dataEndpointEnabled: bool?
		@description('The endpoint protocol settings. IPv4AndIPv6 requires the Premium SKU and enabled dedicated data endpoints; ACR Tasks are not supported in this mode.')
		endpointProtocol: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.endpointProtocol
		@description('The metadata search setting')
		metadataSearch: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.metadataSearch
		@description('Specifies whether Tasks are allowed to bypass the network rules for this container registry.')
		networkRuleBypassAllowedForTasks: bool?
		@description('Specifies whether trusted Azure services may bypass registry network rules.')
		networkRuleBypassOptions: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.networkRuleBypassOptions?
		@description('The network rule set. Requires: sku.name == \'Premium\'.')
		networkRuleSet: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.networkRuleSet?
		@description('The policies.')
		@sealed()
		@validate(
			value =>
				value.retentionPolicy.?status != 'enabled' || value.softDeletePolicy.?status != 'enabled',
			'Retention and soft delete policies cannot both be enabled.'
		)
		policies: {
			@description('The export policy. Disabling exports requires the Premium SKU and disabled public network access.')
			exportPolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.policies.exportPolicy
			@description('The quarantine policy.')
			quarantinePolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.policies.quarantinePolicy
			@description('The retention policy. Enabling retention requires the Premium SKU.')
			retentionPolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.policies.retentionPolicy
			@description('The soft-delete policy.')
			softDeletePolicy: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.policies.softDeletePolicy
		}
		@description('The network access mode.')
		publicNetworkAccess: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.publicNetworkAccess
		@description('Specifies whether regional endpoints are enabled. Enabling them requires the Premium SKU.')
		regionalEndpoints: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.properties.regionalEndpoints
	}
	@description('The SKU.')
	@sealed()
	sku: {
		@description('The SKU name of the container registry.')
		name:
			| 'Basic'
			| 'Premium'
			| 'Standard'
	}
	@description('The tags.')
	tags: resourceInput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.tags
}

/* RESOURCES */

#disable-next-line use-recent-api-versions // endpointProtocol, metadataSearch, and regionalEndpoints are available only in the preview API.
resource ContainerRegistry_registries_ 'Microsoft.ContainerRegistry/registries@2026-03-01-preview' = {
	identity: settings.?identity ?? {
		type: 'None'
	}
	location: settings.location
	name: settings.name
	properties: {
		adminUserEnabled: false
		anonymousPullEnabled: false
		autoGeneratedDomainNameLabelScope: settings.properties.autoGeneratedDomainNameLabelScope
		dataEndpointEnabled: settings.properties.?dataEndpointEnabled
		endpointProtocol: settings.properties.endpointProtocol
		metadataSearch: settings.properties.metadataSearch
		networkRuleBypassAllowedForTasks: settings.properties.?networkRuleBypassAllowedForTasks
		networkRuleBypassOptions: settings.properties.?networkRuleBypassOptions
		networkRuleSet: settings.properties.?networkRuleSet
		policies: {
			azureADAuthenticationAsArmPolicy: {
				status: 'enabled'
			}
			exportPolicy: settings.properties.policies.exportPolicy
			quarantinePolicy: settings.properties.policies.quarantinePolicy
			retentionPolicy: settings.properties.policies.retentionPolicy
			softDeletePolicy: settings.properties.policies.softDeletePolicy
		}
		publicNetworkAccess: settings.properties.publicNetworkAccess
		regionalEndpoints: settings.properties.regionalEndpoints
		roleAssignmentMode: 'AbacRepositoryPermissions'
	}
	sku: settings.sku
	tags: settings.tags
}

/* EXTENSIONS */

resource Authorization_roleAssignments_ 'Microsoft.Authorization/roleAssignments@2022-04-01' = [
	for item in AuthorizationRoleAssignments.CreateArray(
		ContainerRegistry_registries_.id,
		extensions.?Authorization.roleAssignments ?? []
	): {
		name: item.name
		properties: item.properties
		scope: ContainerRegistry_registries_
	}
]

#disable-next-line use-recent-api-versions // 2021-05-01-preview is the newest Diagnostic Settings API; the newest stable version is 2016-09-01.
resource Insights_diagnosticSettings_ 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = [
	for item in extensions.Insights.diagnosticSettings: {
		name: item.name
		properties: item.properties
		scope: ContainerRegistry_registries_
	}
]

/* OUTPUTS */

@description('The ID.')
output id string = ContainerRegistry_registries_.id

@description('The identity.')
output identity resourceOutput<'Microsoft.ContainerRegistry/registries@2026-03-01-preview'>.identity? = ContainerRegistry_registries_.?identity

@description('The name.')
output name string = ContainerRegistry_registries_.name
