metadata author = {
	fullName: 'Stas Sultanov'
	profile: 'https://github.com/stas-sultanov'
}
metadata description = 'Provisions a Microsoft.Web/sites resource.'

/* TYPES */

@export()
@description('dotNet Framework version.')
type DotNetVersion =
	| 'v4.0'
	| 'v6.0'
	| 'v7.0'
	| 'v8.0'
	| 'v9.0'

type IpSecurityRestrictionAction =
	| 'Allow'
	| 'Deny'

@export()
type IpSecurityRestriction = {
	@description('Allow or Deny access for this IP range.')
	action: IpSecurityRestrictionAction

	@description('Information.')
	description: string?

	@description('IP address the security restriction is valid for.')
	ipAddress: string

	@description('IP restriction rule name.')
	name: string
}

@description('Version of TLS required for SSL requests.')
type TlsVersion =
	| '1.1'
	| '1.2'
	| '1.3'

@description('FunctionApp properties.')
type SiteConfig = {
	@description('OpenApi definition path.')
	apiDefinition: string?

	@description('Application settings to be used as Environment Variables.')
	appSettings: object

	@description('List of origins that should be allowed to make cross-origin calls. Use "*" to allow all.')
	corsAllowedOrigins: string[]

	@description('Maximum number of workers that a site can scale out to.')
	@minValue(0)
	@maxValue(200)
	functionAppScaleLimit: int?

	@description('Health check path.')
	healthCheckPath: string?

	@description('Allow clients to connect over http2.0')
	http20Enabled: bool

	@description('List of allowed IP addresses.')
	ipSecurityRestrictions: IpSecurityRestriction[]

	@description('Minimum version of TLS required for SSL requests.')
	minTlsVersion: TlsVersion

	@description('dotNet Framework version.')
	netFrameworkVersion: DotNetVersion

	@description('true if remote debugging is enabled; otherwise, false.')
	remoteDebuggingEnabled: bool
}

@description('FunctionApp properties.')
type Properties = {
	@description('Enable administrative endpoints for functions.')
	functionsRuntimeAdminIsolationEnabled: bool

	@description('HttpsOnly: configures a web site to accept only https requests. Issues redirect for http requests.')
	httpsOnly: bool

	siteConfig: SiteConfig
}

/* PARAMETERS */

@description('Managed Service Identity.')
param identity resourceInput<'Microsoft.Web/sites@2025-03-01'>.identity

@description('Location to deploy the resources.')
param location string

@description('Name of the resource.')
param name string

@description('Service properties.')
param properties Properties

@description('The id of the Web/serverfarms resource.')
param serverFarmId string

@description('Tags to put on the resource.')
param tags object = {}

/* VARIABLES */

var web_serverfarms__id_split = split(
	serverFarmId,
	'/'
)

/* EXISTING RESOURCES */

resource Web_serverFarms_ 'Microsoft.Web/serverfarms@2025-03-01' existing = {
	name: web_serverfarms__id_split[8]
	scope: resourceGroup(
		web_serverfarms__id_split[2],
		web_serverfarms__id_split[4]
	)
}

/* RESOURCES */

resource Web_sites_ 'Microsoft.Web/sites@2025-03-01' = {
	identity: identity
	kind: 'functionapp'
	location: location
	name: name
	properties: {
		autoGeneratedDomainNameLabelScope: 'TenantReuse'
		#disable-next-line BCP037 // bicep has only old api
		functionsRuntimeAdminIsolationEnabled: properties.functionsRuntimeAdminIsolationEnabled
		httpsOnly: properties.httpsOnly
		serverFarmId: Web_serverFarms_.id
		#disable-next-line BCP073 // in API definition this property is read only
		state: 'Stopped'
	}
	tags: tags
}

resource Web_sites_basicPublishingCredentialsPolicies__FTP 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2025-03-01' = {
	name: 'ftp'
	parent: Web_sites_
	properties: {
		allow: false
	}
}

resource Web_sites_basicPublishingCredentialsPolicies__SCM 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2025-03-01' = {
	name: 'scm'
	parent: Web_sites_
	properties: {
		allow: false
	}
}

resource Web_sites_config__AppSettings 'Microsoft.Web/sites/config@2025-03-01' = {
	name: 'appsettings'
	parent: Web_sites_
	properties: union(
		properties.siteConfig.appSettings,
		{
			FUNCTIONS_EXTENSION_VERSION: '~4'
			FUNCTIONS_WORKER_RUNTIME: 'dotnet-isolated'
		}
	)
}

resource Web_sites_config__Metadata 'Microsoft.Web/sites/config@2025-03-01' = {
	name: 'metadata'
	parent: Web_sites_
	properties: {
		CURRENT_STACK: 'dotnet'
	}
}

resource Web_sites_config__Web 'Microsoft.Web/sites/config@2025-03-01' = {
	name: 'web'
	parent: Web_sites_
	properties: {
		apiDefinition: {
			url: (!contains(
					properties,
					'apiDefinition'
				) || empty(properties.siteConfig.?apiDefinition))
				? null
				: 'https://${Web_sites_.properties.defaultHostName}${properties.siteConfig.apiDefinition!}'
		}
		cors: {
			allowedOrigins: properties.siteConfig.corsAllowedOrigins
		}
		defaultDocuments: []
		ftpsState: 'Disabled'
		functionAppScaleLimit: properties.siteConfig.?functionAppScaleLimit
		healthCheckPath: properties.siteConfig.?healthCheckPath
		http20Enabled: properties.siteConfig.http20Enabled
		ipSecurityRestrictions: properties.siteConfig.ipSecurityRestrictions
		minTlsVersion: properties.siteConfig.minTlsVersion
		netFrameworkVersion: properties.siteConfig.netFrameworkVersion
		remoteDebuggingEnabled: properties.siteConfig.remoteDebuggingEnabled
		use32BitWorkerProcess: false
	}
}

resource ManagedIdentity_identities_ 'Microsoft.ManagedIdentity/identities@2024-11-30' existing = {
	scope: Web_sites_
	name: 'default'
}

/* OUTPUTS */

@description('The id.')
output id string = Web_sites_.id

@description('The identity.')
output identity object = union(
	Web_sites_.identity,
	{
		clientId: ManagedIdentity_identities_.?properties.?clientId
	}
)

@description('The name.')
output name string = Web_sites_.name

@description('The properties.')
output properties object = {
	defaultHostName: Web_sites_.properties.defaultHostName
}
