# The workflow to check Bicep templates with compile-time validation

name: Check

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/check.yml"
      - "src/**"
      - "tools/Sync-ApiVersions.ps1"
      - "tools/Bicep-Build.ps1"

jobs:

  build:

    name: Check

    permissions:
      # Required to checkout the repo
      contents: read

    runs-on: ubuntu-latest

    steps:
    - name: Upgrade Bicep
      run: az bicep upgrade

    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify API Versions
      shell: pwsh
      run: ./tools/Sync-ApiVersions.ps1 ./src

    - name: Build Bicep Templates
      shell: pwsh
      run: ./tools/Bicep-Build.ps1 ./src
